spring:
  application:
    name: chat-service-gpt
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: chatuser
    password: chatpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

server:
  port: 8080

logging:
  level:
    com.sesac: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.data.redis: DEBUG
